name: Generate ASCII Artwork

on: push

jobs:
  build_job_1:
    runs-on: ubuntu-latest
    steps:
      - name: Execute Shell Scripts
        run: sudo apt-get install cowsay -y

      - name: Execute Cowsay CMD
        run: cowsay -f dragon "Run Dragon" >> dragon.txt

      - name: sleep for 30 seconds
        run: sleep 30

  

  test_job_2:
    runs-on: ubuntu-latest
    steps:
      - name: sleep for 10 seconds
        run: sleep 10

      - name: Test File Exists
        run: grep -i "dragon" dragon.txt

  deploy_job_3:
    runs-on: ubuntu-latest
    steps:
      - name: sleep for 10 seconds
        run: sleep 10

#      runs-on: ubuntu-latest
#      steps:
#      - name: Checkout Repo
#        uses: actions/checkout@v4

#      - name: Execute Shell Scripts
#        run: |
#          chmod +x ascii-script.sh
#          ./ascii-script.sh

#      - name: Install Cowsay Program
#        run: sudo apt-get install cowsay -y

#      - name: Execute Cowsay CMD
#        run: cowsay -f dragon "Rin For Cover..." >> dragon.txt

#      - name: Test File Exists
#        run: grep -i "dragon" dragon.txt

#      - name: Read File
#        run: cat dragon.txt

      - name: Checkout Repo Files
        run: ls -al
